name: Test

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Make Test
        run: make test
